### ISSUE TITLE
JQuery CDN的替换有遗漏

### ISSUE THREAD

**Issue by Seevil** [racaljk/tieba_cloud#7]
# JQuery CDN的替换有遗漏
### 遗漏文件路径

`\public\manual_bind.html`
`\lib\updater.php`

**Comment by racaljk** [comment]
已修复

话说那两个文件改不改都一样![t](http://static.tieba.baidu.com/tb/editor/images/client/image_emoticon25.png)

**Comment by Seevil** [comment]
强迫症没办法>_<
