### ISSUE TITLE
加入贴吧云签到联盟的问题

### ISSUE THREAD

**Issue by CoolSpring8** [racaljk/tieba_cloud#8]
你好,
当我在贴吧云管理面板点击"加入贴吧云签到联盟"再点击"愿意"后,跳转到的网址是
http://www.racalinux.cn/common_sign.php?website=我的网站绝对路径
后来是手动换成http://www.racalinux.cn/common_sign.php?website=我的网站网址才行的
这个不知道是不是BUG
(看了一下admin.php里是 href="http://www.racalinux.cn/common_sign.php?website='.str_replace('\\', '/',dirname(__FILE__)).'" )

另外似乎直接访问http://www.racalinux.cn/common_sign.php?website=网址 可以恶意添加不是贴吧云的网站233333333333

**Comment by racaljk** [comment]
贴吧云签到联盟已经弃坑了,主要是用户太少,在下一个stable版本中会删除
